//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DolphyNotes {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texto {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texto() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DolphyNotes.Texto", typeof(Texto).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se activo el siempre al frente.
        /// </summary>
        public static string ActivarAlFrente {
            get {
                return ResourceManager.GetString("ActivarAlFrente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se activaron los botones.
        /// </summary>
        public static string ActivarBotones {
            get {
                return ResourceManager.GetString("ActivarBotones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se activo la fijacion de la ventana.
        /// </summary>
        public static string ActivarFijacion {
            get {
                return ResourceManager.GetString("ActivarFijacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se desactivo el siempre al frente.
        /// </summary>
        public static string DesactivarAlFrente {
            get {
                return ResourceManager.GetString("DesactivarAlFrente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se desactivaron los botones.
        /// </summary>
        public static string DesactivarBotones {
            get {
                return ResourceManager.GetString("DesactivarBotones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se desactivo la fijacion de la ventana.
        /// </summary>
        public static string DesactivarFijacion {
            get {
                return ResourceManager.GetString("DesactivarFijacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al abrir el archivo:.
        /// </summary>
        public static string ErrorAbrir {
            get {
                return ResourceManager.GetString("ErrorAbrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el archivo de configuracion.
        /// </summary>
        public static string ErrorConfiguracion {
            get {
                return ResourceManager.GetString("ErrorConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar el archivo:.
        /// </summary>
        public static string ErrorGuardar {
            get {
                return ResourceManager.GetString("ErrorGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extensión no soportada del archivo:.
        /// </summary>
        public static string ExtensionNoSoportada {
            get {
                return ResourceManager.GetString("ExtensionNoSoportada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El idioma cambio a.
        /// </summary>
        public static string IdiomaCambio {
            get {
                return ResourceManager.GetString("IdiomaCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propiedades.
        /// </summary>
        public static string Propiedades {
            get {
                return ResourceManager.GetString("Propiedades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Archivos RTF |*.rtf|Archivos de texto|*.txt|Todos los archivos|*.*.
        /// </summary>
        public static string TipoArchivos {
            get {
                return ResourceManager.GetString("TipoArchivos", resourceCulture);
            }
        }
    }
}
